--
-- ER/Studio 8.0 SQL Code Generation
-- Company :      Japan
-- Project :      BUGϵͳ.DM1
-- Author :       Microsoft
--
-- Date Created : Wednesday, May 25, 2016 21:06:53
-- Target DBMS : MySQL 5.x
--

CREATE TABLE BUG(
    BUG_ID         INT             AUTO_INCREMENT,
    PRIORITY       INT,
    TITLE          VARCHAR(200),
    MODULE_ID      INT             NOT NULL,
    STEPS          TEXT,
    COMMENTS       TEXT,
    STATUS_CD      VARCHAR(30),
    DETECTED_BY    VARCHAR(30)     NOT NULL,
    DETECTED_DT    DATETIME,
    FIXED_BY       VARCHAR(30)     NOT NULL,
    FIXED_DT       DATETIME,
    CLOSED_BY      VARCHAR(30)     NOT NULL,
    CLOSED_DT      DATETIME,
    PRIMARY KEY (BUG_ID)
)ENGINE=INNODB
;



CREATE TABLE BUG_HIS(
    BUG_HIS_ID    INT            AUTO_INCREMENT,
    MDF_FLD_NM    VARCHAR(50)    NOT NULL,
    BEFORE_VAL    TEXT,
    AFTER_VAL     TEXT,
    BUG_ID        INT            NOT NULL,
    PRIMARY KEY (BUG_HIS_ID)
)ENGINE=INNODB
;



CREATE TABLE M_USER(
    USER_ID         VARCHAR(30)     NOT NULL,
    LAST_NM         VARCHAR(20),
    FIRST_NM        VARCHAR(20),
    LOGIN_PWD       VARCHAR(200),
    EMAIL           VARCHAR(50),
    USER_TYPE_CD    VARCHAR(20),
    PRIMARY KEY (USER_ID)
)ENGINE=INNODB
;



CREATE TABLE MODULE(
    MODULE_ID        INT            AUTO_INCREMENT,
    PRT_MODULE_ID    INT            NOT NULL,
    MODULE_NM        VARCHAR(50),
    PROJECT_ID       INT            NOT NULL,
    PRIMARY KEY (MODULE_ID)
)ENGINE=INNODB
;



CREATE TABLE PROJ_USER_ROLE(
    PUR_ID        CHAR(10)       NOT NULL,
    USER_ID       VARCHAR(30)    NOT NULL,
    PROJECT_ID    INT            NOT NULL,
    ROLE_NM       VARCHAR(50),
    PRIMARY KEY (PUR_ID)
)ENGINE=INNODB
;



CREATE TABLE PROJECT(
    PROJECT_ID    INT            AUTO_INCREMENT,
    PROJECT_NM    VARCHAR(50),
    PRIMARY KEY (PROJECT_ID)
)ENGINE=INNODB
;



ALTER TABLE BUG ADD CONSTRAINT RefM_USER2 
    FOREIGN KEY (DETECTED_BY)
    REFERENCES M_USER(USER_ID)
;

ALTER TABLE BUG ADD CONSTRAINT RefMODULE4 
    FOREIGN KEY (MODULE_ID)
    REFERENCES MODULE(MODULE_ID)
;

ALTER TABLE BUG ADD CONSTRAINT RefM_USER5 
    FOREIGN KEY (FIXED_BY)
    REFERENCES M_USER(USER_ID)
;

ALTER TABLE BUG ADD CONSTRAINT RefM_USER6 
    FOREIGN KEY (CLOSED_BY)
    REFERENCES M_USER(USER_ID)
;


ALTER TABLE BUG_HIS ADD CONSTRAINT RefBUG1 
    FOREIGN KEY (BUG_ID)
    REFERENCES BUG(BUG_ID)
;


ALTER TABLE MODULE ADD CONSTRAINT RefPROJECT3 
    FOREIGN KEY (PROJECT_ID)
    REFERENCES PROJECT(PROJECT_ID)
;

ALTER TABLE MODULE ADD CONSTRAINT RefMODULE9 
    FOREIGN KEY (PRT_MODULE_ID)
    REFERENCES MODULE(MODULE_ID)
;


ALTER TABLE PROJ_USER_ROLE ADD CONSTRAINT RefM_USER7 
    FOREIGN KEY (USER_ID)
    REFERENCES M_USER(USER_ID)
;

ALTER TABLE PROJ_USER_ROLE ADD CONSTRAINT RefPROJECT8 
    FOREIGN KEY (PROJECT_ID)
    REFERENCES PROJECT(PROJECT_ID)
;


